### ISSUE TITLE
Home page does not render properly in dark mode.

### ISSUE THREAD

**Issue by terrypumbaa** [natster101s/Minerva-Neue-2.0#1]
Tried to test new dark mode by using the home page. Box around the content is all white and text is basically unreadable.
![image](https://user-images.githubusercontent.com/113104638/189101313-f821309f-3b59-4557-aabe-4ceb1a9a434a.png)

**Comment by natster101s** [comment]
I have implemented a fix for this issue, it is not perfect but the text is now readable.
